apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - image: postgres:latest
        name: postgres
        env:
          # Use secret in real usage
        - name: postgres_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 5432
          name: mysql
        volumeMounts:
        - name: postgres-persistent-storage
          mountPath: /var/lib/postgres
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: postgres-pv-claim
